In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/raw_data.csv')

In [4]:
df

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,$46476.6380809961,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,$54174.6879482406,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,UAS,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,NaN,Male,Accenture,Canada,$46784.6308786279,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,$57486.4955595568,1947.0
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,$,952.0
6,207.0,Modesta Batterson,3/28/2018,NaN,Female,Intel,India,NaN,32.0
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,NaN,1901.0
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,UAS,$28602.4353770562,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,$47119.1747795038,920.0
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,NaN,1286.0
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,$55804.9256874294,NaN
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,$44191.4731284524,46.0
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,$,568.0
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,$44481.7651905881,1553.0
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,$55719.9621570482,1013.0
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,$33767.5099948119,1920.0
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,$7101.35196996979,1952.0
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,$43363.0787072359,1668.0

In [9]:
df.iloc[9]=df.iloc[9].fillna({'id':210,'Employee Full Name':'Jim Carry','DOB':'1/1/1970','email':'jim.carry@gmail.com','gender':'Male',
                              'Company':'Amazon','Income.1':12349.556,'Income.2':2345})

In [10]:
df

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,$46476.6380809961,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,$54174.6879482406,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,UAS,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,NaN,Male,Accenture,Canada,$46784.6308786279,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,$57486.4955595568,1947.0
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,$,952.0
6,207.0,Modesta Batterson,3/28/2018,NaN,Female,Intel,India,NaN,32.0
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,NaN,1901.0
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,UAS,$28602.4353770562,NaN
9,210.0,Jim Carry,1/1/1970,jim.carry@gmail.com,Male,Amazon,NaN,12349.556,2345.0
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,$47119.1747795038,920.0
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,NaN,1286.0
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,$55804.9256874294,NaN
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,$44191.4731284524,46.0
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,$,568.0
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,$44481.7651905881,1553.0
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,$55719.9621570482,1013.0
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,$33767.5099948119,1920.0
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,$7101.35196996979,1952.0
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,$43363.0787072359,1668.0

In [11]:
df.iloc[3]=df.iloc[3].fillna({'email':'grame.crossier@gmail.com'})

In [12]:
df

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,$46476.6380809961,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,$54174.6879482406,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,UAS,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,grame.crossier@gmail.com,Male,Accenture,Canada,$46784.6308786279,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,$57486.4955595568,1947.0
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,$,952.0
6,207.0,Modesta Batterson,3/28/2018,NaN,Female,Intel,India,NaN,32.0
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,NaN,1901.0
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,UAS,$28602.4353770562,NaN
9,210.0,Jim Carry,1/1/1970,jim.carry@gmail.com,Male,Amazon,NaN,12349.556,2345.0
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,$47119.1747795038,920.0
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,NaN,1286.0
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,$55804.9256874294,NaN
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,$44191.4731284524,46.0
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,$,568.0
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,$44481.7651905881,1553.0
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,$55719.9621570482,1013.0
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,$33767.5099948119,1920.0
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,$7101.35196996979,1952.0
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,$43363.0787072359,1668.0

In [13]:
df.iloc[6]=df.iloc[6].fillna({'email':'modesta.batterson@gmail.com'})

In [14]:
df

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,$46476.6380809961,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,$54174.6879482406,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,UAS,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,grame.crossier@gmail.com,Male,Accenture,Canada,$46784.6308786279,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,$57486.4955595568,1947.0
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,$,952.0
6,207.0,Modesta Batterson,3/28/2018,modesta.batterson@gmail.com,Female,Intel,India,NaN,32.0
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,NaN,1901.0
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,UAS,$28602.4353770562,NaN
9,210.0,Jim Carry,1/1/1970,jim.carry@gmail.com,Male,Amazon,NaN,12349.556,2345.0
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,$47119.1747795038,920.0
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,NaN,1286.0
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,$55804.9256874294,NaN
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,$44191.4731284524,46.0
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,$,568.0
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,$44481.7651905881,1553.0
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,$55719.9621570482,1013.0
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,$33767.5099948119,1920.0
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,$7101.35196996979,1952.0
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,$43363.0787072359,1668.0

In [15]:
df['Country'].unique()

array(['India', 'USA', 'UAS', 'Canada', nan, 'Russia'], dtype=object)

In [16]:
df['Country'] = df['Country'].replace({'UAS':'USA'})

In [17]:
df['Country'].unique()

array(['India', 'USA', 'Canada', nan, 'Russia'], dtype=object)

In [19]:
df['Country']=df['Country'].fillna(df['Country'].mode()[0])

In [20]:
df['Country'].unique()

array(['India', 'USA', 'Canada', 'Russia'], dtype=object)